from typing import Protocol, runtime_checkable

@runtime_checkable
class StatePort(Protocol):
    async def get(self, call_sid: str) -> dict: ...
    async def save(self, call_sid: str, state: dict, ttl: int = 3600) -> None: ...
    async def delete(self, call_sid: str) -> None: ...
