-- Migration 009: Agent Plans Table (Planner Service persistence)
-- Required by services/planner-service/src/server.ts
-- Stores task graph DAGs created by the Planner Engine

CREATE TABLE IF NOT EXISTS agent_plans (
  id            UUID PRIMARY KEY,
  company_id    TEXT NOT NULL,
  goal          TEXT NOT NULL,
  tasks         JSONB NOT NULL DEFAULT '[]',
  status        TEXT NOT NULL DEFAULT 'pending'
                  CHECK (status IN ('pending','running','completed','failed','cancelled')),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  completed_at  TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_agent_plans_company_id ON agent_plans(company_id);
CREATE INDEX IF NOT EXISTS idx_agent_plans_status ON agent_plans(status);
CREATE INDEX IF NOT EXISTS idx_agent_plans_created_at ON agent_plans(created_at DESC);

COMMENT ON TABLE agent_plans IS 'Persistent task graph DAGs generated by the Planner Service for AI agent goal execution.';
COMMENT ON COLUMN agent_plans.tasks IS 'JSONB array of TaskNode objects with id, name, action, dependencies, status, and result.';
